name: Docker Image CI

on: 
  push: 
    branches:
      - yannick

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 16
      uses: actions/setup-node@v1
      with:
        node-version: '16'
    # - name: Install yarn and run unittest
    #   run: |
    #     npm start
    #     npm test
    #   env: 
    #     CI: true
    - name: docker login
      env: 
        DOCKER_USER: ${{secrets.USERNAME}}
        DOCKER_PASSWORD: ${{secrets.PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p DOCKER_PASSWORD

    - name: Build the Docker Image
      run: docker build . --file Dockerfile --tag yandjoumbi:$(date +%s)  

    - name: Docker push
      run: docker push ${{secrets.USERNAME}}/yandjoumbi


 
    