name: Deploy to ECR

on: 
  push: 
    branches:
      - yannick

jobs:
  build:
    
    name: Build Image
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Use Node.js 16
      uses: actions/setup-node@v1
      with:
        node-version: '16'
    # - name: Install yarn and run unittest
    #   run: |
    #     npm start
    #     npm test
    #   env: 
    #     CI: true

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      #uses: aws-actions/amazon-ecr-login@v1   
      run: aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/v6n8a7u8

    - name: Build, tag, and push image to Amazon ECR
      env:
        #ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REGISTRY: v6n8a7u8 
        ECR_REPOSITORY: full-stack-docker-frontend
        IMAGE_TAG: nodejs_demo_image
      run: |
        docker build -t $ECR_REGISTRY .
        docker tag $ECR_REGISTRY:$IMAGE_TAG public.ecr.aws/v6n8a7u8/$ECR_REGISTRY:$IMAGE_TAG 
        docker push public.ecr.aws/v6n8a7u8/$ECR_REPOSITORY:$IMAGE_TAG


 
    